# Generated by Django 3.1.1 on 2020-10-22 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginApp', '0002_userinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='userKey',
            field=models.TextField(),
        ),
    ]
